config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: [:index]
  devise_for :users
  resources :carts, only: [:show, :buy]
  resources :users, only: [:edit, :update, :show]
  resources :products do
	  collection { post :import }
  end
  post '/products/:id/add', to: 'products#add'
  post '/carts/:id/buy', to: 'carts#buy'
  post '/products/:id/remove', to: 'products#remove'
  root to: "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_and_belongs_to_many :products
	def cart_total
		products.sum{|p| p.price}
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_action :set_cart, only: [:show, :edit, :update, :destroy]

	# GET /carts
	# GET /carts.json
	def index
		@carts = Cart.all
	end

	# GET /carts/1
	# GET /carts/1.json
	def show
		if @cart.id != current_user.cart.id
			redirect_to :root, notice: "Carro incorrecto."
		end
	end

	def buy
		current_user.carts << Cart.new
		redirect_to :root
	end

	# GET /carts/new
	def new
		@cart = Cart.new
	end

	# GET /carts/1/edit
	def edit
	end

	# POST /carts
	# POST /carts.json
	def create
		@cart = Cart.new(cart_params)

		respond_to do |format|
			if @cart.save
				format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
				format.json { render :show, status: :created, location: @cart }
			else
				format.html { render :new }
				format.json { render json: @cart.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /carts/1
	# PATCH/PUT /carts/1.json
	def update
		respond_to do |format|
			if @cart.update(cart_params)
				format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
				format.json { render :show, status: :ok, location: @cart }
			else
				format.html { render :edit }
				format.json { render json: @cart.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /carts/1
	# DELETE /carts/1.json
	def destroy
		@cart.destroy
		respond_to do |format|
			format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_cart
		@cart = Cart.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def cart_params
		params.fetch(:cart, {})
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(cart) do |f| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Tu Carro
	<small>
		<%= "("+pluralize(@cart.products.count, "Articulo")+")" %>
	</small>
</h2>
<% if @cart.products.empty? %>
	<div class="col-md-8 col-md-offset-3">
		<h3>Tu carro esta vacio. Agrega un <%= link_to "producto!", products_url %></h3>
	</div>
<% else %>
	<div class="col-md-12 product" style="margin-bottom:15px">
		<div class="product-header" style="color:#aaa">
			<div class="col-md-3">Nombre del producto</div>
			<div class="col-md-2">Cantidad</div>
			<div class="col-md-2">Precio</div>
			<div class="col-md-2">Eliminar</div>
		</div>
	</div>
	<% @cart.products.to_set.each do |p| %>
		<div class="col-md-12 product" style="margin-bottom:15px">
			<div class="col-md-1"><img src="http://placehold.it/80x80"></div>
			<div class="product-text" style="margin-top:30px">
				<div class="col-md-2"><%= link_to p.name.titleize, p %></div>
				<div class="col-md-2"><%= @cart.products.select{|pr| pr.id==p.id}.count %></div>
				<div class="col-md-2" style="font-size:16px;font-weight:700;color:#333">US <%= number_to_currency(p.price, precision: 2) %><small style="color:#aaa;font-size:12px;font-weight:300"> / unidad</small></div>
				<div class="col-md-2">
					<%= link_to product_path(p)+"/remove", :method => :post do %>
						<i class="fa fa-remove" aria-hidden="true"></i>
					<% end %>
				</div>
			</div>
		</div>
	<% end %>
	<div class="col-md-4" style="float:right">
		<h3 style="float:right">Total del Carro: <strong style="color:#e62">US <%= number_to_currency(@cart.cart_total, precision: 2) %></strong></h3>
		<%= link_to cart_path(@cart)+"/buy", :method => :post do %>
			<button class="btn btn-success" style="float:right;background:#e62;color:#fff;font-weight:700">
				Comprar todo
			</button>
		<% end %>
	</div>
<% end %>