config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: [:index]
  devise_for :users
  resources :carts, only: [:show, :buy]
  resources :users, only: [:edit, :update, :show]
  resources :products do
	  collection { post :import }
  end
  post '/products/:id/add', to: 'products#add'
  post '/carts/:id/buy', to: 'carts#buy'
  post '/products/:id/remove', to: 'products#remove'
  root to: "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
	has_and_belongs_to_many :products
	has_and_belongs_to_many :categories, as: :subcategories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>Nueva Categoria</h1>

<%= render 'form', category: @category %>

<%= link_to 'Volver', root_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-md-2">
		<h4>Categorias</h4>
		<% Category.all.each do |cat| %>
			<div class="cat" style="line-height:28px">
				<% if cat.id == @category.id %>
					<strong>
						<%= link_to cat.name.titleize, cat %>
					</strong>
				<% else %>
					<%= link_to cat.name.titleize, cat %>
				<% end %>
			</div>
		<% end %>

	</div>
	<div class="col-md-10">
		<div class="container">
			<% @category.products.each_with_index do |product,idx| %>
				<% if idx%3 == 0 %>
					<div class="row" style="margin-bottom:30px">
					<% end %>

					<div class="col-md-3">
						<%= link_to product do %>
							<%= image_tag "http://placehold.it/220x220", size: "220x220" %>
							<h3><%= product.name.titleize %></h3>
							<span class="price" style="font-size:16px;font-weight:700;line-height:20px;color:#e62">US <%= number_to_currency(product.price, precision: 2) %><small style="color:#aaa;font-size:12px;font-weight:300"> / unidad</small></span>
							<%= link_to product_path(product)+"/add", :method => :post do%>
								<span style="padding-top:30px;float:right;margin-right:45px">
									<i class="fa fa-cart-plus" aria-hidden="true"></i>
									Agregar al carro
								</span>
							<% end %>
						<% end %>
					</div>
					<% if idx%3 == 2 %>
						</div>
					<% end %>
				<% end %>
		</div>
	</div>
</div>