config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: [:index]
  devise_for :users
  resources :carts, only: [:show, :buy]
  resources :users, only: [:edit, :update, :show]
  resources :products do
	  collection { post :import }
  end
  post '/products/:id/add', to: 'products#add'
  post '/carts/:id/buy', to: 'carts#buy'
  post '/products/:id/remove', to: 'products#remove'
  root to: "products#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	has_and_belongs_to_many :carts
	has_and_belongs_to_many :categories
	accepts_nested_attributes_for :categories

	def self.import(file)
		spreadsheet = open_spreadsheet(file)
		header = spreadsheet.row(1)
		(2..spreadsheet.last_row).each do |i|
			row = Hash[[header, spreadsheet.row(i)].transpose]
			product = find_by_id(row["id"]) || new
			product.attributes = row.to_hash
			if (not product.name.blank?) and (not product.price.blank?)
				product.save!
			end
		end
	end

	def self.open_spreadsheet(file)
		case File.extname(file.original_filename)
		when ".csv" then Roo::CSV.new(file.path, csv_options: {encoding: "iso-8859-1:utf-8"})
		when ".xls" then Roo::Excel.new(file.path)
		when ".xlsx" then Roo::Excelx.new(file.path)
		else raise "Archivo invalido: #{file.original_filename}"
		end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :set_product, only: [:show, :edit, :update, :destroy, :add, :remove]

	# GET /products
	# GET /products.json
	def index
		@products = Product.all
		if current_user.nil?
			new_user = User.new(email: "guest"+rand(1024).to_s+"@guest-domain.com", password: rand(36**8).to_s(36))
			new_user.save
			sign_in(new_user)
			@cart = Cart.new
			new_user.carts << @cart
			@cart.save
		else
			@cart = current_user.cart
		end
	end

	# POST /products/1/add
	# POST /products/1/add.json
	def add
		@cart = current_user.cart
		@cart.products << @product
		redirect_to products_url
	end

	def remove
		@cart = current_user.cart
		@cart.products.delete(@product)
		redirect_to current_user.cart
	end
	#
	# GET /products/1
	# GET /products/1.json
	def show
	end

	# GET /products/new
	def new
		@product = Product.new
	end

	# GET /products/1/edit
	def edit
		@categories = Category.all
	end

	# POST /products
	# POST /products.json
	def create
		@product = Product.new(product_params)

		respond_to do |format|
			if @product.save
				format.html { redirect_to @product, notice: 'Product was successfully created.' }
				format.json { render :show, status: :created, location: @product }
			else
				format.html { render :new }
				format.json { render json: @product.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /products/1
	# PATCH/PUT /products/1.json
	def update
		respond_to do |format|
			p product_params
			if @product.update(product_params)
				format.html { redirect_to @product, notice: 'Product was successfully updated.' }
				format.json { render :show, status: :ok, location: @product }
			else
				format.html { render :edit }
				format.json { render json: @product.errors, status: :unprocessable_entity }
			end
		end
	end

	def import
		Product.import(params[:file])
		redirect_to root_url, notice: "Productos importados."
	end

	# DELETE /products/1
	# DELETE /products/1.json
	def destroy
		@product.destroy
		respond_to do |format|
			format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_product
		@product = Product.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def product_params
		params.require(:product).permit(:name, :price, :description, category_ids: [])
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Nombre" %>
    <%= f.text_field :name, required: true, class: "form-control", style: "width:300px" %>
  </div>

  <div class="form-group">
    <%= f.label :price, "Precio" %>
    <%= f.text_field :price, required: true, class: "form-control", style: "width:100px" %>
  </div>

  <div class="form-group">
    <%= f.label :description, "Descripcion" %>
    <%= f.text_area :description, class: "form-control", rows: 3, style: "width:600px" %>
  </div>

  <div class="form-group">
    <%= f.label :categories, "Categorias" %>
	<br/>
	<%= f.select :category_ids, options_for_select(Category.all.collect {|c| [c.name, c.id]}), {}, {:multiple => true} %>
  </div>

  <div class="actions">
    <%= f.submit "Guardar Producto"%>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editar Producto</h1>

<%= render 'form', product: @product %>

<%= link_to 'Ver', @product %> |
<%= link_to 'Volver', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-md-2">
		<h4>Categorias</h4>
		<% Category.all.each do |cat| %>
			<div class="cat" style="line-height:28px">
				<%= link_to cat.name.titleize, cat %>
			</div>
		<% end %>

	</div>
	<div class="col-md-10">
		<div class="container">
			<% @products.each_with_index do |product,idx| %>
				<% if idx%3 == 0 %>
					<div class="row" style="margin-bottom:30px">
					<% end %>
					<div class="col-md-3">
						<%= link_to product do %>
							<%= image_tag "http://placehold.it/220x220", size: "220x220" %>
							<h3><%= product.name.titleize %></h3>
							<span class="price" style="font-size:16px;font-weight:700;line-height:20px;color:#e62">US <%= number_to_currency(product.price, precision: 2) %><small style="color:#aaa;font-size:12px;font-weight:300"> / unidad</small></span>
							<%= link_to product_path(product)+"/add", :method => :post do%>
								<span style="padding-top:30px;float:right;margin-right:45px">
									<i class="fa fa-cart-plus" aria-hidden="true"></i>
									Agregar al carro
								</span>
							<% end %>
						<% end %>
					</div>
					<% if idx%3 == 2 %>
						</div>
					<% end %>
				<% end %>
		</div>
	</div>

	<br>
</div>
<hr>
<div class="row">
	<div class="col-md-offset-2 col-md-4">
		<div class="row">
			<h4>Importar Productos</h4>

			<%= form_tag import_products_path, multipart: true do %>
				<%= file_field_tag :file, required: true %>
				<br/>
				<%= submit_tag "Importar" %>
			<% end %>

			<hr>
		</div>
		<div class="row">
			<h4>
				<%= link_to 'Nuevo Producto', new_product_path %>
			</h4>
		</div>
	</div>

app/views/products/new.html.erb
<h1>Nuevo Producto</h1>

<%= render 'form', product: @product %>

<%= link_to 'Volver', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-6">
	<img src="http://placehold.it/500x550">
</div>

<div class="col-md-6">
	<span style="line-height:55px">
		<h3>
			<%= @product.name.titleize %>
		</h3>
		<span style="color:#f90;font-weight:700">
			<i class="fa fa-star" aria-hidden="true"></i>
			<i class="fa fa-star" aria-hidden="true"></i>
			<i class="fa fa-star" aria-hidden="true"></i>
			<i class="fa fa-star" aria-hidden="true"></i>
			<i class="fa fa-star" aria-hidden="true"></i>
			5.0 <small style="color:#aaa;font-weight:300">(1 voto)</small>
		</span>

		<div class="price" style="font-size:24px;font-weight:700;line-height:32px;color:#e62">
			US <%= number_to_currency(@product.price, precision: 2) %><small style="color:#aaa;font-size:12px;font-weight:300"> / unidad</small>
		</div>

		<%= link_to product_path(@product)+"/add", :method => :post do%>
			<button class="btn btn-danger" style="background:#e62;color:#fff;font-weight:300">
				<i class="fa fa-cart-plus" aria-hidden="true"></i>
				Agregar al carro
			</button>
		<% end %>
		<div>
			<strong>Descripcion del producto:</strong>
			<%= @product.description %>
		</div>
		<div>
			<strong>Categorias:</strong>
			<%= @product.categories.map{|c| c.name.titleize}.join(", ") %>
		</div>

		<%= link_to 'Editar', edit_product_path(@product) %> |
		<%= link_to 'Volver', products_path %>
	</span>
</div>